version: '3.0'
services:
  httpd:
    container_name: httpd
    build:
      context: .
      dockerfile: Dockerfile
    image: dd-dockerreg.academy.grads.al-labs.co.uk:5000/httpd
    restart: always
    ports:
      - 80:80
