---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: httpd
      track: canary
  template:
    metadata:
      labels:
        app: app
        track: canary
    spec:
      containers:
      - name: httpd
        image: $DOCKER_IMAGE_NAME_HTTPD:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m


kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-canary
spec:
  type: NodePort
  selector:
    app: train-schedule
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000

---
