kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-canary
spec:
  type: NodePort
  selector:
    app: train-schedule
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        track: canary
    spec:
      containers:
      - name: httpd
        image: $DOCKER_IMAGE_NAME_HTTPD:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: httpd-svc
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
spec:
  selector:
    app: app
  ports:
  - name: httpd-port
    port: 80
    protocol: TCP
    targetPort: 8081

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpd-ingress
spec:
  rules:
  - host: httpd.dev.dd-kube.academy.grads.al-labs.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: httpd-svc
          servicePort: 80
