apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-canary
  labels:
    app: httpd
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: httpd
      track: canary
  template:
    metadata:
      labels:
        app: httpd
        track: canary
    spec:
      containers:
      - name: httpd
        image: $DOCKER_IMAGE_NAME_HTTPD:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd-svc-canary
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
spec:
  selector:
    app: httpd
  ports:
  - name: port-2
    port: 80
    protocol: TCP
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpd-ingress-canary
spec:
  rules:
  - host: canary.httpd.dev.dd-kube.academy.grads.al-labs.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: httpd-svc-canary
          servicePort: 80
